### ISSUE TITLE
AppKit Is Done: Default Selection Question

### ISSUE THREAD

**Issue by aaronrogers** [kean/articles#4]
In the [article](https://github.com/kean/articles/blob/master/2021-02-24-appkit-is-done.markdown), the portion about the default selection in a list using `isDefaultItemActive` isn't clear.  It doesn't appear to work for me.  Instead, there is nothing selected and selection appears to be cancelled every time I try to select something in the list.  What am I missing?

**Comment by kean** [comment]
It works pretty reliably for me. Make sure you pass `isDefaultItemActive` to a single `NavigationLink`.
